alauda changes
AlaudaDevops/harbor-helm pull request #2
Opened 2024-12-09 07:08 UTC by airycanon

2024-12-16 13:27 UTC, nanjingfm requested changes

2024-12-16 13:27 UTC, nanjingfm commented on templates/core/core-pre-upgrade-job.yaml
> +        image: {{ .Values.global.registry.address }}/{{ .Values.global.images.core.repository }}:{{ .Values.global.images.core.tag }}
可以写个 自定义函数来统一生成组件镜像地址

2024-12-16 13:27 UTC, nanjingfm commented on templates/core/core-pre-upgrade-job.yaml
> -        {{- if .Values.database.external.existingSecret }}
感觉改动的地方可以加个注释，比如"解决敏感信息明文展示的问题"

2024-12-16 13:27 UTC, nanjingfm commented on templates/exporter/exporter-dpl.yaml
> +        image: "{{ .Values.global.registry.address }}/{{ .Values.global.images.exporter.repository }}:{{ .Values.global.images.exporter.tag }}"
写个自定义 function

2024-12-16 13:27 UTC, nanjingfm commented on templates/jobservice/jobservice-dpl.yaml
> +        image: "{{ .Values.global.registry.address }}/{{ .Values.global.images.jobservice.repository }}:{{ .Values.global.images.jobservice.tag }}"
写个 helper 函数

2024-12-16 13:27 UTC, nanjingfm commented on templates/jobservice/jobservice-dpl.yaml
> +      {{- if and .Values.persistence.enabled (has "file" .Values.jobservice.jobLoggers) }}
增加 feature 注释

2024-12-16 13:27 UTC, nanjingfm commented on templates/nginx/deployment.yaml
> +        image: "{{ .Values.global.registry.address }}/{{ .Values.global.images.nginx.repository }}:{{ .Values.global.images.nginx.tag }}"
写个 helper 函数

2024-12-16 13:27 UTC, nanjingfm commented on templates/oidc/oidc-job.yaml
> +          image: "{{ .Values.global.registry.address }}/{{ .Values.global.images.nginx.repository }}:{{ .Values.global.images.nginx.tag }}"
写个 helper 函数

2024-12-16 13:27 UTC, nanjingfm commented on templates/portal/configmap.yaml
> +            {{- if not .Values.portal.swagger.enabled }}
加个注释

2024-12-16 13:27 UTC, nanjingfm commented on values.yaml
> +  secret: "0123456789ABCDEF"
看注释会随机生成一个，是不是留空比较好

2024-12-16 13:27 UTC, nanjingfm commented on values.yaml
> +  xsrfKey: "A3F7B4175EB3C1DA2F477685808422A5"
同上

2024-12-16 13:27 UTC, nanjingfm commented on values.yaml
> +  secret: "0123456789ABCDEF"
同上

2024-12-16 13:29 UTC, nanjingfm requested changes
留了几个评论

2024-12-17 07:34 UTC, airycanon commented on templates/core/core-pre-upgrade-job.yaml
> -        {{- if .Values.database.external.existingSecret }}
删除的代码，不太好加注释。

2024-12-17 07:41 UTC, nanjingfm approved these changes

2024-12-17 07:42 UTC, merged